name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-manual:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-version: "latest", python-version: "3.10" }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba install -n test sagelib=10.3
          echo "sagelib == 10.3" >> $CONDA_PREFIX/conda-meta/pinned
          mamba env update --quiet -n test -f environment.yml
          mamba env update --quiet -n test -f doc/environment.yml
          conda list
      - name: install surface-dynamics
        shell: bash -l {0}
        run: |
          pip install --no-index .
      - name: build documentation
        shell: bash -l {0}
        run: |
          sphinx-build -b html -n doc/source html/surface-dynamics --color -a -E -W
          touch html/surface-dynamics/.nojekyll
      - name: detect broken links
        shell: bash -l {0}
        run: |
          python -m http.server 8880 --directory html &
          sleep 1
          # We ignore _modules since sphinx puts all modules in the module
          # overview but does not generate pages for .pyx modules.
          # We ignore warnings. They are usually 302 (temporary redirect) which
          # we do not consider a problem.
          linkchecker --check-extern --ignore-url=_modules/ --no-warnings http://localhost:8880
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: html/surface-dynamics
          TARGET_FOLDER: docs/
        if: ${{ github.event_name == 'push' }}

env:
  MAKEFLAGS: -j4
  SAGE_NUM_THREADS: 4
